export interface BibliotecaEUS {
  documentName: string; // "Aia - Biblioteca Municipal"
  documentDescription: string; // "Aia - Biblioteca Municipal"
  libraryTimeTable: string; // "De lunes a jueves: 10:00 - 13:00 y 17:00 - 20:00. Viernes: 10:00 - 14:45"
  librarySummerTimeTable: string; // "Vacaciones escolares: 10:30 - 13:00. Agosto y Semana Santa cerrado" / De lunes a viernes: 10:00 - 14:00. Martes: 16:00 - 19:00. Agosto cerrado
  latitudelongitude: string; // "43.236524,-2.148162"
  latwgs84: string; // "43.236524"
  lonwgs84: string; // "-2.148162"
  placename: string; // "Aia - Udal Liburutegia"
  address: string; // "Gozategi enparantza, 3 3"
  municipality: string; // "Aia"
  municipalitycode: string; // ""
  postalcode: string; // "20.809"
  territory: string; // "Gipuzkoa"
  territorycode: string; // "administrative_area_level_2"
  country: string; // ""
  countrycode: string; // ""
  phone: string; // "943 130 924 "
  email: string; // "kulturetxe@aia.eus"
  webpage: string; // "http://www.aiako.com/eu/html/9/1643.shtml"
  friendlyUrl: string; // "https://www.euskadi.eus/biblioteca/aia-biblioteca-municipal/web01-a2kulond/es/"
  physicalUrl: string; // "https://www.euskadi.eus/web01-a2kulond/es/contenidos/biblioteca/x42t_biblio_8/es_def/index.shtml"
  dataXML: string; // "https://www.euskadi.eus/contenidos/biblioteca/x42t_biblio_8/es_def/data/es_r01dtpd1600d4c9e055d8c047295f25b4f0deb91a3"
  metadataXML: string; // "https://www.euskadi.eus/contenidos/biblioteca/x42t_biblio_8/r01Index/x42t_biblio_8-idxContent.xml"
  zipFile: string; // "https://www.euskadi.eus/contenidos/biblioteca/x42t_biblio_8/opendata/x42t_biblio_8.zip"
}
